insert into STUDENT(STUDENTID, NAME,PHONE) VALUES (1,'A','121');
insert into STUDENT(STUDENTID, NAME,PHONE) VALUES (2,'B','122');
insert into STUDENT(STUDENTID, NAME,PHONE) VALUES (3,'C','123');
COMMIT;